name: HomeLab Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: deployment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        
      - name: Install PM2 if not installed
        run: |
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 is not installed, installing now..."
            npm install -g pm2
          fi

      - name: Deploy with PM2
        run: |
          git pull
          npm ci
          npm run build
          pm2 restart ecosystem.config.js