name: HomeLab Deployment

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    environment: deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy
        with:
          script: |
            cd portfolio # Specify the path to your app directory on the server
            git pull
            npm install
            npm run build
            pm2 restart ecosystem.config.js # Replace with your PM2 config
